version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=MySecureP@ss!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    # Simple TCP healthcheck; no sqlcmd required
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/1433'"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s

  web:
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    image: arbox/web:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__Default=Server=db,1433;Database=ArboxDb;User Id=sa;Password=MySecureP@ss!;Encrypt=True;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5246:80"