name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore Arbox.EmployeeManagement.sln

      - name: Build
        run: dotnet build Arbox.EmployeeManagement.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test Arbox.EmployeeManagement.sln --no-build --configuration Release --verbosity normal
